# Generated by Django 5.0 on 2024-01-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
